[build]
  command = "npm run test && npm run build" # Run tests before building
  publish = "dist" # Or the directory where your build output is

[dev]
  command = "npm run dev" # Command for development build
  publish = "dist" # Or the directory for development build output

[build.environment]
  NODE_VERSION = "18"

[test]
  command = "npm run test:coverage"
  publish = "dist"